import { NextResponse } from 'next/server';
import { requireOperationsSession } from '@/server/operations-http';
import { materials,visits } from '@/server/services/operations';
import { operationalWorkbook,type ExcelCell } from '@/server/operations-xlsx';
import { privateHeaders,supplyFailure } from '@/server/supply-http';
import { daySchema } from '@/server/operations-input';
import { formStatusLabel } from '@/lib/form-status';
export const dynamic='force-dynamic';
export async function GET(request:Request){const a=await requireOperationsSession();if(!a.ok)return a.response;
 try{const p=new URL(request.url).searchParams,projects=p.getAll('project'),kind=p.get('kind'),day=kind==='visits'?daySchema.parse(p.get('day')):'';
  let rows:ExcelCell[][],name:string;
  if(kind==='visits'){const result=await visits(a.actor,day,projects);name='Jornada';rows=[['Día','Horario','Proyecto / zona','Sitio','Nombre','Tipo','Código tarea','Técnicos','Estado','Resultado de jornada','Pendientes del sitio','Jornada cerrada','Última modificación'],...result.items.map(v=>[v.day,v.shift==='FUERA_DE_HORARIO'?'Fuera de horario':'Horario laboral',v.project,v.siteCode,v.siteName,v.taskType,v.taskCode,v.technicians.join(' / '),v.status,v.outcome,v.pending.join('\n'),v.closed?'Sí':'No',v.updatedAt])];}
  else{const result=await materials(a.actor,projects);name='Control de insumos';rows=[['Formulario','Cell ID','Estado','Tipo','Respuesta','Cantidad Sytex','Fecha','Enlace','Factura','Descarga en Intra','Proyecto','Nombre sitio','Técnico','Provisto por','Incluido / no incluido','Conteo revisado','Cantidad descargada Intra','Diferencia','Comprobantes adjuntos','Falta revisar / descargar','Cambió desde la revisión','Observaciones','Grupo','Índice','Fuente','Fecha fuente','Última revisión'],...result.map(r=>{const project=r.review?.project??r.projects.join(' / ');return [r.formulario,r.siteCode,formStatusLabel(r.formStatus),/\bMPC\b|preventiv/i.test(project)?'PREVENTIVO':/\bMCC|correctiv/i.test(project)?'CORRECTIVO':'',r.description,r.quantity===null?null:Number(r.quantity),r.editedAt?.slice(0,10)??'',r.link??'',r.review?.invoiceNumber||'Sin factura',r.changed?'REVISAR_CAMBIO_DE_FUENTE':r.review?.intraStatus??'PENDIENTE',project,r.siteName,r.technician,r.provider??'',r.review?.classification??'PENDIENTE',r.review?.countedQuantity==null?null:Number(r.review.countedQuantity),r.review?.intraQuantity==null?null:Number(r.review.intraQuantity),r.difference,r.files.length,r.missing?'Sí':'No',r.changed?'Sí':'No',r.review?.notes??'',r.group,r.index,r.source,r.syncedAt,r.review?.updatedAt??''];})];}
  const bytes=operationalWorkbook([{name,rows},{name:'Datos del reporte',rows:[['Campo','Valor'],['Generado por',a.actor.user.name],['Fecha de generación',new Date().toISOString()],['Filtro',projects.join(' / ')||'Todas las zonas autorizadas'],['Origen','Sytex / PostgreSQL y control manual FNET'],['Intra','Estados declarados manualmente, sin conexión automática'],['Jornadas cerradas','Conservan una fotografía de las visitas y pendientes al cierre']]}]);
  return new NextResponse(new Uint8Array(bytes),{headers:{...privateHeaders,'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename="FNET-${kind==='visits'?'jornada-'+day:'insumos'}.xlsx"`}});
 }catch(e){return supplyFailure(e);}}
