import { strToU8, zipSync } from 'fflate';
/** A cell is text, a number, empty, or text that opens a web link (only https links are kept). */
export type ExcelCell=string|number|null|{text:string;link:string};
const webLink=(v:ExcelCell):v is {text:string;link:string}=>typeof v==='object'&&v!==null&&/^https:\/\//i.test(v.link);
const cellText=(v:ExcelCell)=>v===null?'':typeof v==='object'?v.text:String(v);
const xml=(value:string)=>value.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').slice(0,32767).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function col(i:number){let s='';for(i++;i>0;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;}
export function operationalWorkbook(sheets:{name:string;rows:ExcelCell[][]}[]):Uint8Array {
  const files:Record<string,Uint8Array>={},ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
  const add=(path:string,content:string)=>files[path]=strToU8('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+content);
  add('[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
  add('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  add('xl/workbook.xml',`<workbook xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
  add('xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
  add('xl/styles.xml',`<styleSheet xmlns="${ns}"><fonts count="3"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font><font><u/><sz val="11"/><color rgb="FF0563C1"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF253B53"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf></cellXfs></styleSheet>`);
  sheets.forEach((s,i)=>{const width=Math.max(1,...s.rows.map(r=>r.length)),end=`${col(width-1)}${Math.max(1,s.rows.length)}`;
    const links=s.rows.flatMap((r,n)=>r.flatMap((v,c)=>n>0&&webLink(v)?[{ref:`${col(c)}${n+1}`,url:v.link}]:[]));
    if(links.length)add(`xl/worksheets/_rels/sheet${i+1}.xml.rels`,`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${links.map((l,k)=>`<Relationship Id="rId${k+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${xml(l.url)}" TargetMode="External"/>`).join('')}</Relationships>`);
    add(`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="${ns}" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><dimension ref="A1:${end}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="30"/><cols>${Array.from({length:width},(_,c)=>`<col min="${c+1}" max="${c+1}" width="${Math.min(55,Math.max(15,...s.rows.slice(0,200).map(r=>cellText(r[c]).length+2)))}" customWidth="1"/>`).join('')}</cols><sheetData>${s.rows.map((r,n)=>`<row r="${n+1}"${n===0?' ht="36" customHeight="1"':''}>${r.map((v,c)=>typeof v==='number'&&Number.isFinite(v)?`<c r="${col(c)}${n+1}" s="${n===0?1:0}" t="n"><v>${v}</v></c>`:`<c r="${col(c)}${n+1}" s="${n===0?1:webLink(v)?2:0}" t="inlineStr"><is><t xml:space="preserve">${xml(cellText(v))}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${end}"/>${links.length?`<hyperlinks>${links.map((l,k)=>`<hyperlink ref="${l.ref}" r:id="rId${k+1}"/>`).join('')}</hyperlinks>`:''}</worksheet>`);
  });return zipSync(files,{level:6});
}
