"use client";
import { useEffect,useState,type FormEvent } from 'react';
import type { OperationsCatalog,Visit,VisitStatus } from '@/contracts/operations';
import { Feedback,opCall,operationsUrl,operationToday,splitTechnicians,useCatalog,useOperation,ZoneFavorites } from './operations-common';
import s from './operations.module.css';
const statuses:Record<VisitStatus,string>={PLANIFICADO:'Planificado',EN_CURSO:'En curso',REALIZADO:'Realizado',CON_PENDIENTES:'Realizado con pendientes',CANCELADO:'Cancelado / no realizado'};
type DayData={items:Visit[];closed:{project:string;closedAt:string}[]};
export function DailySchedule(){
 const zones=useCatalog(),op=useOperation(),[day,setDay]=useState(operationToday),[data,setData]=useState<DayData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[dialog,setDialog]=useState<Visit|'new'|null>(null),[history,setHistory]=useState<{day:string;project:string;closedAt:string}[]>([]);
 const filter=zones.projects.join('|');
 useEffect(()=>{if(!zones.data)return;let active=true;const timer=setTimeout(()=>{setLoading(true);opCall<DayData>(operationsUrl('visits',zones.projects,day)).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active){setError(e.message);setData(null);}}).finally(()=>{if(active)setLoading(false);});},0);return()=>{active=false;clearTimeout(timer);};},[day,filter,revision,zones.data]); // eslint-disable-line react-hooks/exhaustive-deps
 const refreshed=()=>setRevision(v=>v+1);
 return <section className={s.app}><header className={s.heading}><div><div className={s.kicker}>OPERACIÓN DIARIA · TODOS LOS PROYECTOS</div><h1>Cronograma de coordinadores</h1><p className={s.note}>Planificá sitios y técnicos, sumá correctivos y dejá registrado el resultado de cada jornada.</p></div><button onClick={refreshed}>Actualizar</button></header>
 <ZoneFavorites state={zones}/><Feedback error={error||zones.error}/><Feedback {...op}/>
 <div className={s.toolbar}><label>Día de trabajo<input type="date" value={day} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label><button className={s.primary} disabled={!zones.data} onClick={()=>setDialog('new')}>+ Programar sitio / correctivo</button>
 <button disabled={loading||!data?.items.some(v=>!v.closed)||op.busy} onClick={()=>{if(window.confirm('¿Cerrar la jornada de los proyectos visibles? El resultado quedará guardado y no podrá editarse.'))void op.run(async()=>{await opCall('/api/operations',{action:'close',day,projects:zones.projects});refreshed();op.setSuccess('Jornada cerrada y guardada en el historial. Podés descargar su Excel.');});}}>Cerrar jornada</button>
 {zones.data&&<a className={s.button} href={operationsUrl('visits',zones.projects,day,true)}>Descargar Excel del día</a>}
 <button disabled={!zones.data||op.busy} onClick={()=>op.run(async()=>{setHistory(await opCall(operationsUrl('history',zones.projects)));})}>Ver jornadas guardadas</button></div>
 {!!history.length&&<div className={s.card}><h2>Historial de jornadas</h2><div className={s.favorites}>{history.map(h=><button key={h.day+h.project} onClick={()=>setDay(h.day)}>{h.day} · {h.project}</button>)}</div></div>}
 {loading?<p role="status">Consultando la jornada…</p>:data&&<><div className={s.stats}><div>Sitios programados<strong>{data.items.length}</strong></div><div>Realizados<strong>{data.items.filter(v=>['REALIZADO','CON_PENDIENTES'].includes(v.status)).length}</strong></div><div>Sitios con pendientes<strong>{data.items.filter(v=>v.pending.length||v.status==='CON_PENDIENTES').length}</strong></div><div>Proyectos cerrados<strong>{data.closed.length}</strong></div></div>
 {data.closed.length>0&&<p className={s.success}>Jornada guardada: {data.closed.map(v=>v.project).join(', ')}. Sus visitas y pendientes se conservan como estaban al cierre.</p>}
 {!data.items.length&&<div className={s.card}>Todavía no hay sitios programados para este día y filtro. Agregá la primera visita.</div>}
 {data.items.map(v=><article className={s.card} key={v.id}><div className={s.heading}><div><span className={s.kicker}>{v.project} · {v.taskType} {v.taskCode}</span><h2>{v.siteCode} {v.siteName&&'· '+v.siteName}</h2><p>Técnicos: {v.technicians.join(' / ')}</p></div><div><strong>{statuses[v.status]}</strong><br/><button disabled={v.closed} onClick={()=>setDialog(v)}>{v.closed?'Jornada cerrada':'Editar / registrar resultado'}</button></div></div>
 {v.outcome&&<p>Resultado: {v.outcome}</p>}{v.pending.length>0?<div className={s.pending}><strong>Atención: pendientes registrados en este sitio</strong>{v.pending.map((p,i)=><p key={i}>{p}</p>)}</div>:<p className={s.note}>Sin pendientes vinculados en la fuente consultada; esto no confirma que el sitio no tenga otros pendientes.</p>}</article>)}</>}
 {dialog&&zones.data&&<div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-label="Programar o editar visita"><div className={s.heading}><h2>{dialog==='new'?'Programar sitio':'Resultado de la visita'}</h2><button onClick={()=>setDialog(null)}>Cerrar ✕</button></div><VisitForm catalog={zones.data} day={day} projects={zones.projects} visit={dialog==='new'?null:dialog} onSaved={()=>{setDialog(null);refreshed();}}/></section></div>}
 </section>;
}
function VisitForm({catalog,day,projects,visit,onSaved}:{catalog:OperationsCatalog;day:string;projects:string[];visit:Visit|null;onSaved:()=>void}){
 const op=useOperation(),[requestKey]=useState(()=>crypto.randomUUID()),[project,setProject]=useState(visit?.project??projects[0]??catalog.projects[0]??''),[type,setType]=useState(visit?.taskType??'PREVENTIVO'),[task,setTask]=useState(visit?.taskCode??''),[site,setSite]=useState(visit?.siteCode??''),[name,setName]=useState(visit?.siteName??''),[technicians,setTechnicians]=useState(visit?.technicians.join(', ')??'');
 const options=catalog.tasks.filter(t=>t.project===project&&t.type===type);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await op.run(async()=>{await opCall('/api/operations',visit?{action:'updateVisit',id:visit.id,version:visit.version,technicians:splitTechnicians(technicians),status:f.get('status'),outcome:f.get('outcome')}:{action:'visit',requestKey,day,project,siteCode:site,siteName:name,taskType:type,taskCode:task,technicians:splitTechnicians(technicians),status:f.get('status'),outcome:f.get('outcome')});onSaved();});}
 return <form onSubmit={submit}><p className={s.note}>{day} · Los cambios se guardan en FNET sin modificar Sytex. Si surge un correctivo sin código, dejá la tarea vacía y completá sitio y técnicos.</p><div className={s.fields}><label>Proyecto / zona<select disabled={!!visit} required value={project} onChange={e=>{setProject(e.target.value);setTask('');setSite('');setName('');}}>{catalog.projects.map(p=><option key={p}>{p}</option>)}</select></label><label>Tipo de visita<select disabled={!!visit} value={type} onChange={e=>{setType(e.target.value);setTask('');}}><option value="PREVENTIVO">Preventivo</option><option value="CORRECTIVO">Correctivo / imprevisto</option><option value="OTRO">Otro</option></select></label>
 <label className={s.wide}>Tarea Sytex (opcional)<input disabled={!!visit} list="operations-tasks" value={task} placeholder="Código de tarea o dejar vacío" onChange={e=>{setTask(e.target.value);const t=options.find(t=>t.code===e.target.value);if(t){setSite(t.siteCode);setName(t.siteName);setTechnicians(t.technicians.join(', '));}}}/><datalist id="operations-tasks">{options.map(t=><option key={t.code} value={t.code}>{t.siteCode} · {t.description}</option>)}</datalist></label>
 <label>Código de sitio<input disabled={!!visit} required value={site} onChange={e=>setSite(e.target.value)} maxLength={200}/></label><label>Nombre de sitio<input disabled={!!visit} value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label className={s.wide}>Técnicos (separados por coma)<input required value={technicians} onChange={e=>setTechnicians(e.target.value)} placeholder="Nombre o correo del técnico, otro técnico"/></label>
 <label>Estado<select name="status" defaultValue={visit?.status??'PLANIFICADO'}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className={s.wide}>Resultado / pendientes de la jornada<textarea name="outcome" maxLength={4000} defaultValue={visit?.outcome??''} placeholder="Trabajo realizado, impedimentos, pendientes o motivo de cancelación"/></label></div><Feedback {...op}/><button className={s.primary} disabled={op.busy}>{op.busy?'Guardando…':'Guardar visita'}</button></form>;
}
