"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { ReadOnlyResourcePage } from "./read-only-resource-page";
import type { SupplyOverview, SupplyInvoice, SupplyHandoff, SupplyMovement, InvoiceLine } from "@/contracts/supply-control";
import styles from "./supplies-control.module.css";
import { SytexSupplyControl } from './sytex-supply-control';
import operationalStyles from './operations.module.css';

const messages: Record<string, string> = {
  UNAUTHENTICATED: "Ingresá con tu cuenta para trabajar con los datos reales.", FORBIDDEN: "Esta función requiere una cuenta administradora.",
  INPUT_INVALID: "Revisá los campos indicados. Usá punto para los decimales y un código FO completo.",
  SUPPLY_DATABASE_UNAVAILABLE: "No se pudo acceder a la base de datos. Reintentá; no se guardaron cambios sin confirmar.",
  STALE_VERSION: "El registro cambió mientras lo editabas. Cerrá el detalle y volvé a abrirlo antes de reintentar.",
  STOCK_CHANGED_OR_INSUFFICIENT: "Cambió el saldo disponible o la entrega lo supera. Volvé a abrir la factura.",
  INSUFFICIENT_REMAINING: "El consumo supera el saldo del técnico.", EXHAUSTED_REQUIRES_ALL_REMAINING: "Para marcar que se acabó, distribuí todo el saldo entre los formularios.",
  DUPLICATE_FORM: "Unificá las cantidades: el mismo formulario figura más de una vez.",
  ATTACHMENT_REQUIRED: "Adjuntá al menos un comprobante antes de confirmar la descarga o la carga en Intra.",
  CONCURRENT_OR_DUPLICATE_RECORD: "Ya existe esa factura o el registro cambió. Actualizá el listado antes de reintentar.",
  DATE_OUT_OF_RANGE: "La fecha no puede ser futura ni anterior a la compra o entrega correspondiente.",
  FILE_TYPE_INVALID: "El archivo debe ser un PDF o una imagen PNG, JPG o WebP válida.", FILE_TOO_LARGE: "Cada archivo puede pesar hasta 8 MB.",
  INVOICE_FILE_LIMIT: "Cada factura admite hasta 6 archivos y 24 MB en total.",
  RESET_UPLOAD_BEFORE_CHANGING_FILES: "Primero reabrí la carga en Intra para cambiar los archivos.",
  MENDEL_TRANSACTION_NOT_FOUND: "Ese identificador no está en las compras importadas de Mendel.",
  RETURN_STOCK_ALREADY_DELIVERED: "El material devuelto ya fue entregado otra vez. No se puede revertir esa devolución.",
  MOVEMENT_CANNOT_REVERSE: "Ese movimiento ya fue revertido o no se puede corregir.", REQUEST_KEY_REUSED: "La solicitud anterior ya se guardó con otros datos. Actualizá el listado.",
};
async function call<T>(url: string, method = "GET", body?: unknown): Promise<T> {
  const response = await fetch(url, { method, cache: "no-store", ...(body ? { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {}) });
  const payload = await response.json();
  if (!response.ok) throw new Error((messages[payload.code] ?? `No se pudo completar la operación (${payload.code ?? response.status}).`) + (payload.fields?.length ? ` Campos: ${payload.fields.join(", ")}.` : ""));
  return payload;
}
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const date = (value: string | null) => value ? new Date(value).toLocaleString("es-AR", { timeZone: "America/Argentina/Buenos_Aires" }) : "Pendiente";
const quantity = (value: string) => Number(value).toLocaleString("es-AR", { maximumFractionDigits: 3 });
const money = (invoice: SupplyInvoice) => Number(invoice.amount).toLocaleString("es-AR", { style: "currency", currency: invoice.currency });
const newLine = () => ({ description: "", quantity: "", unit: "unidad" });
type Dialog = { type: "new" } | { type: "invoice"; id: string } | { type: "handoff"; id: string } | { type: "delivery"; line: InvoiceLine; invoiceId: string } | null;

export function SuppliesControl() {
  const [tab, setTab] = useState("control"), [data, setData] = useState<SupplyOverview | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [now, setNow] = useState(() => Date.now());
  const [search, setSearch] = useState(""), [technician, setTechnician] = useState(""), [invoiceFilter, setInvoiceFilter] = useState(""), [overdue, setOverdue] = useState(false);
  const [invoicePage, setInvoicePage] = useState(1), [handoffPage, setHandoffPage] = useState(1), [revision, setRevision] = useState(0), [dialog, setDialog] = useState<Dialog>(null);
  useEffect(() => {
    if (tab === "sytex" || tab === "control") return;
    let active = true;
    const params = new URLSearchParams({ search, technician, invoiceFilter, overdue: String(overdue), invoicePage: String(invoicePage), handoffPage: String(handoffPage) });
    const timer = setTimeout(() => { setLoading(true); setError(""); setNow(Date.now()); call<SupplyOverview>(`/api/supplies?${params}`).then((value) => { if (active) setData(value); }).catch((e) => { if (active) { setError(e.message); setData(null); } }).finally(() => { if (active) setLoading(false); }); }, 200);
    return () => { active = false; clearTimeout(timer); };
  }, [search, technician, invoiceFilter, overdue, invoicePage, handoffPage, revision, tab]);
  const refreshed = () => setRevision((r) => r + 1);
  const counts = data?.counts;
  if(tab==="control") return <section><nav className={operationalStyles.app}><button onClick={()=>setTab("facturas")}>Facturas y entregas internas</button> · <Link href="/coordinadores">Cuentas de coordinadores</Link></nav><SytexSupplyControl /></section>;
  return <section className={styles.app}>
    <header className={styles.heading}><div><p>OPERACIÓN · DATOS REALES</p><h1>Insumos y facturas</h1><span>Comprobantes, materiales en poder de cada técnico y consumo por formulario.</span></div><button onClick={refreshed} disabled={loading}>Actualizar</button></header>
    <nav className={styles.tabs} aria-label="Secciones de Insumos">{[["control", "Control Sytex / Intra"], ["facturas", "Facturas y entregas"], ["tecnicos", "Materiales por técnico"], ["sytex", "Fuente original"]].map(([key, label]) => <button key={key} aria-pressed={tab === key} onClick={() => setTab(key)}>{label}</button>)}<a href="/coordinadores">Cuentas de coordinadores ↗</a></nav>
    {tab === "control" ? <SytexSupplyControl /> : tab === "sytex" ? <ReadOnlyResourcePage resource="insumos" /> : <>
      <div className={styles.stats}>{[
        ["Facturas registradas", counts?.invoices, () => { setTab("facturas"); setInvoiceFilter(""); }],
        ["Falta comprobante", counts?.missingFiles, () => { setTab("facturas"); setInvoiceFilter("files"); setInvoicePage(1); }],
        ["Falta confirmar descarga", counts?.pendingDownload, () => { setTab("facturas"); setInvoiceFilter("download"); setInvoicePage(1); }],
        ["Falta cargar en Intra", counts?.pendingUpload, () => { setTab("facturas"); setInvoiceFilter("upload"); setInvoicePage(1); }],
        ["Entregas con saldo", counts?.activeHandoffs, () => { setTab("tecnicos"); setOverdue(false); }],
        ["Entregas para revisar", counts?.overdueHandoffs, () => { setTab("tecnicos"); setOverdue(true); setHandoffPage(1); }],
      ].map(([label, value, action]) => <button key={String(label)} onClick={action as () => void}><span>{label as string}</span><strong>{value === undefined ? "—" : value as number}</strong></button>)}</div>
      <p className={styles.note}>Los saldos son del control interno FNET. Los registros de Sytex ayudan a verificar formularios; no descuentan materiales automáticamente. La carga en Intra requiere confirmación manual.</p>
      {error && <div className={styles.error} role="alert">{error}<Link href="/">Volver al inicio / ingresar</Link></div>}
      <div className={styles.toolbar}>{tab === "facturas" ? <><input aria-label="Buscar facturas" placeholder="Proveedor o número de factura" value={search} onChange={(e) => { setSearch(e.target.value); setInvoicePage(1); }} /><select aria-label="Filtrar facturas" value={invoiceFilter} onChange={(e) => { setInvoiceFilter(e.target.value); setInvoicePage(1); }}><option value="">Todas las facturas</option><option value="files">Sin comprobante</option><option value="download">Descarga pendiente</option><option value="upload">Carga en Intra pendiente</option></select><button className={styles.primary} onClick={() => setDialog({ type: "new" })}>+ Registrar factura</button></> : <><select aria-label="Técnico" value={technician} onChange={(e) => { setTechnician(e.target.value); setHandoffPage(1); }}><option value="">Todos los técnicos</option>{data?.technicians.map((t) => <option key={t}>{t}</option>)}</select><label><input type="checkbox" checked={overdue} onChange={(e) => { setOverdue(e.target.checked); setHandoffPage(1); }} /> Solo entregas para revisar</label></>}</div>
      {loading ? <p role="status">Consultando PostgreSQL…</p> : data && (tab === "facturas" ? <><div className={styles.tableWrap}><table><thead><tr><th>Factura / proveedor</th><th>Fecha / total</th><th>Archivos</th><th>Descarga</th><th>Intra</th><th>Detalle</th></tr></thead><tbody>{data.invoices.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.documentType} · {invoice.number}</strong><small>{invoice.supplier}</small></td><td>{invoice.invoiceDate.slice(0, 10)}<small>{money(invoice)}</small></td><td>{invoice.attachments.length} archivo(s)</td><td>{invoice.downloadedAt ? "Confirmada" : "Pendiente"}</td><td>{invoice.uploadedAt ? "Carga confirmada" : "Pendiente"}</td><td><button onClick={() => setDialog({ type: "invoice", id: invoice.id })}>Ver factura</button></td></tr>)}</tbody></table></div>{!data.invoiceCount && <p className={styles.empty}>{invoiceFilter || search ? "No hay facturas con ese filtro." : "Todavía no se registraron facturas. Podés cargar una factura real y adjuntar sus comprobantes."}</p>}<Pager page={invoicePage} count={data.invoiceCount} onPage={setInvoicePage} /></> : <><div className={styles.tableWrap}><table><thead><tr><th>Técnico / sitio</th><th>Material / factura</th><th>Entregado</th><th>Saldo</th><th>Seguimiento</th><th>Acción</th></tr></thead><tbody>{data.handoffs.map((h) => <tr key={h.id}><td><strong>{h.technician}</strong><small>{h.site ?? "Sin sitio informado"}</small></td><td>{h.line.description}<small>{h.line.invoice.number}</small></td><td>{quantity(h.quantityGiven)} {h.line.unit}</td><td>{quantity(h.remaining)} {h.line.unit}</td><td>{h.status === "CLOSED" ? "Sin saldo" : new Date(h.dueAt).getTime() <= now ? <span className={styles.warning}>Revisar · {Math.floor((now - new Date(h.assignedAt).getTime()) / 86400000)} días</span> : `Revisar desde ${new Date(h.dueAt).toLocaleDateString("es-AR")}`}</td><td><button onClick={() => setDialog({ type: "handoff", id: h.id })}>Uso e historial</button></td></tr>)}</tbody></table></div>{!data.handoffCount && <p className={styles.empty}>No hay entregas con ese filtro. Las entregas se registran desde el detalle de una factura.</p>}<Pager page={handoffPage} count={data.handoffCount} onPage={setHandoffPage} /></>)}
    </>}
    {dialog && <div className={styles.overlay}><section role="dialog" aria-modal="true" aria-label="Detalle de insumos" className={styles.dialog}><button className={styles.close} onClick={() => setDialog(null)} aria-label="Cerrar detalle">Cerrar ✕</button>
      {dialog.type === "new" && <NewInvoice onSaved={(id) => { refreshed(); setDialog({ type: "invoice", id }); }} />}
      {dialog.type === "invoice" && <InvoiceDetail key={dialog.id} id={dialog.id} onRefresh={refreshed} onDelivery={(line) => setDialog({ type: "delivery", line, invoiceId: dialog.id })} />}
      {dialog.type === "delivery" && <Delivery line={dialog.line} onSaved={() => { refreshed(); setDialog({ type: "invoice", id: dialog.invoiceId }); }} />}
      {dialog.type === "handoff" && <HandoffDetail key={dialog.id} id={dialog.id} onRefresh={refreshed} />}
    </section></div>}
  </section>;
}
function Pager({ page, count, onPage }: { page: number; count: number; onPage: (p: number) => void }) { return <div className={styles.pager}><button disabled={page <= 1} onClick={() => onPage(page - 1)}>Anterior</button><span>{count} registros · página {page} de {Math.max(1, Math.ceil(count / 50))}</span><button disabled={page * 50 >= count} onClick={() => onPage(page + 1)}>Siguiente</button></div>; }
function useOperation() {
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), locked = useRef(false);
  const run = async (action: () => Promise<void>) => { if (locked.current) return; locked.current = true; setBusy(true); setError(""); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo completar la operación."); } finally { locked.current = false; setBusy(false); } };
  return { error, busy, run };
}
function Feedback({ error }: { error: string }) { return error ? <p className={styles.error} role="alert">{error}</p> : null; }
function NewInvoice({ onSaved }: { onSaved: (id: string) => void }) {
  const [lines, setLines] = useState([newLine()]), op = useOperation(), key = useRef(crypto.randomUUID());
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await op.run(async () => { const result = await call<{ id: string }>("/api/supplies/invoices", "POST", { requestKey: key.current, supplier: f.get("supplier"), documentType: f.get("documentType"), number: f.get("number"), invoiceDate: f.get("invoiceDate"), amount: f.get("amount"), currency: f.get("currency"), mendelTransactionId: f.get("mendelTransactionId"), lines }); onSaved(result.id); }); }
  return <><h2>Registrar factura real</h2><p>Ingresá los datos del comprobante. Luego podrás adjuntar archivos y entregar los materiales.</p><form onSubmit={submit} className={styles.form}><div className={styles.fields}><label>Proveedor<input name="supplier" required maxLength={200} /></label><label>Tipo<select name="documentType">{["A", "B", "C", "E", "TICKET", "OTRO"].map((t) => <option key={t}>{t}</option>)}</select></label><label>Número<input name="number" required maxLength={80} /></label><label>Fecha<input name="invoiceDate" type="date" required defaultValue={today()} max={today()} /></label><label>Total<input name="amount" required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" placeholder="0.00" /></label><label>Moneda<select name="currency"><option>ARS</option><option>USD</option></select></label><label>Transacción Mendel (opcional)<input name="mendelTransactionId" maxLength={80} placeholder="Identificador exacto de la compra" /></label></div>
    <h3>Materiales comprados</h3><p>La cantidad comprada define el saldo que se puede entregar. Una compra de Mendel por sí sola no informa esas cantidades.</p>
    {lines.map((line, i) => <div className={styles.line} key={i}><input required aria-label={`Material ${i + 1}`} placeholder="Descripción del material" value={line.description} onChange={(e) => setLines((rows) => rows.map((row, j) => j === i ? { ...row, description: e.target.value } : row))} /><input required aria-label={`Cantidad ${i + 1}`} inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" placeholder="Cantidad" value={line.quantity} onChange={(e) => setLines((rows) => rows.map((row, j) => j === i ? { ...row, quantity: e.target.value } : row))} /><select aria-label={`Unidad ${i + 1}`} value={line.unit} onChange={(e) => setLines((rows) => rows.map((row, j) => j === i ? { ...row, unit: e.target.value } : row))}>{["unidad", "litro", "metro", "kg", "rollo", "otro"].map((u) => <option key={u}>{u}</option>)}</select><button type="button" onClick={() => setLines((rows) => rows.filter((_, j) => j !== i))}>Quitar</button></div>)}
    <button type="button" disabled={lines.length >= 100} onClick={() => setLines((rows) => [...rows, newLine()])}>+ Material</button><Feedback error={op.error} /><button className={styles.primary} disabled={op.busy}>{op.busy ? "Guardando…" : "Guardar factura"}</button></form></>;
}
type InvoiceDetails = SupplyInvoice & { events: Array<{ id: string; type: string; createdAt: string; actorId: string; detail: Record<string, unknown> }> };
function InvoiceDetail({ id, onRefresh, onDelivery }: { id: string; onRefresh: () => void; onDelivery: (line: InvoiceLine) => void }) {
  const [invoice, setInvoice] = useState<InvoiceDetails | null>(null), [reference, setReference] = useState(""), op = useOperation();
  const load = useCallback(async () => { const value = await call<InvoiceDetails>(`/api/supplies/invoices/${id}`); setInvoice(value); setReference(value.intraReference ?? ""); }, [id]);
  useEffect(() => { let active = true; call<InvoiceDetails>(`/api/supplies/invoices/${id}`).then((v) => { if (active) { setInvoice(v); setReference(v.intraReference ?? ""); } }).catch((e) => { if (active) void op.run(async () => { throw e; }); }); return () => { active = false; }; }, [id]); // eslint-disable-line react-hooks/exhaustive-deps
  const status = (action: string) => op.run(async () => { if (!invoice) return; await call(`/api/supplies/invoices/${id}`, "PATCH", { version: invoice.version, action, intraReference: reference }); await load(); onRefresh(); });
  async function upload(files: FileList | null) { if (!files?.length) return; const selected = Array.from(files); await op.run(async () => { let completed = 0; try { for (const file of selected) { const form = new FormData(); form.set("file", file); const response = await fetch(`/api/supplies/invoices/${id}/files`, { method: "POST", body: form }); if (!response.ok) { const e = await response.json(); throw new Error(messages[e.code] ?? `No se adjuntó ${file.name}.`); } completed++; } } catch (e) { throw new Error(`${completed} de ${selected.length} archivos guardados. ${e instanceof Error ? e.message : "Reintentá los restantes."}`); } finally { await load(); onRefresh(); } }); }
  async function download() { await op.run(async () => { const response = await fetch(`/api/supplies/invoices/${id}/download`, { method: "POST" }); if (!response.ok) { const e = await response.json(); throw new Error(messages[e.code] ?? "No se descargó el paquete."); } const blob = await response.blob(), url = URL.createObjectURL(blob), a = document.createElement("a"); a.href = url; a.download = `factura-${invoice?.number.replace(/[^\w-]/g, "_") ?? id}.zip`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); }); }
  return <><Feedback error={op.error} />{!invoice ? <p>Cargando factura…</p> : <><h2>Factura {invoice.documentType} · {invoice.number}</h2><p>{invoice.supplier} · {invoice.invoiceDate.slice(0, 10)} · <strong>{money(invoice)}</strong></p>{invoice.mendelTransactionId && <p>Compra Mendel: {invoice.mendelTransactionId} <a href="/compras">Ver compras</a></p>}
    <h3>Comprobantes e imágenes</h3><p>PDF, JPG, PNG o WebP. Hasta 8 MB por archivo, 6 archivos y 24 MB por factura.</p><div className={styles.files}>{invoice.attachments.map((file) => <div key={file.id}><a href={`/api/supplies/files/${file.id}`} target="_blank" rel="noreferrer">{file.fileName} ↗</a><small>{Math.ceil(file.byteCount / 1024)} KB</small><button disabled={op.busy || !!invoice.uploadedAt} onClick={() => { const reason = window.prompt("Motivo para quitar el archivo (queda en el historial):"); if (reason) void op.run(async () => { await call(`/api/supplies/files/${file.id}`, "DELETE", { version: invoice.version, reason }); await load(); onRefresh(); }); }}>Quitar</button></div>)}</div>
    {!invoice.attachments.length && <p className={styles.warning}>Falta adjuntar el comprobante.</p>}
    <label className={styles.upload}>Adjuntar archivos<input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" multiple disabled={op.busy || !!invoice.uploadedAt} onChange={(e) => { void upload(e.target.files); e.target.value = ""; }} /></label>
    <div className={styles.actions}><button disabled={op.busy || !invoice.attachments.length} onClick={download}>Descargar paquete para Intra</button><button disabled={op.busy || !invoice.attachments.length} onClick={() => status(invoice.downloadedAt ? "RESET_DOWNLOAD" : "DOWNLOADED")}>{invoice.downloadedAt ? "Reabrir descarga" : "Confirmar que lo descargué"}</button></div><p>Descarga: {date(invoice.downloadedAt)}. Se confirma después de guardar los archivos en tu equipo.</p>
    <h3>Carga en la Intra de Claro</h3><label>Referencia o número de carga (opcional)<input value={reference} onChange={(e) => setReference(e.target.value)} maxLength={500} /></label><div className={styles.actions}><button disabled={op.busy || !invoice.attachments.length} onClick={() => status(invoice.uploadedAt ? "RESET_UPLOAD" : "UPLOAD_CONFIRMED")}>{invoice.uploadedAt ? "Reabrir carga en Intra" : "Confirmar: ya cargué factura y archivos en Intra"}</button></div><p>Carga confirmada: {date(invoice.uploadedAt)}</p>
    <h3>Materiales y entregas</h3><div className={styles.tableWrap}><table><thead><tr><th>Material</th><th>Comprado</th><th>Disponible para entregar</th><th>Acción</th></tr></thead><tbody>{invoice.lines.map((line) => <tr key={line.id}><td>{line.description}</td><td>{quantity(line.quantity)} {line.unit}</td><td>{quantity(line.availableQuantity)} {line.unit}</td><td><button disabled={Number(line.availableQuantity) <= 0 || op.busy} onClick={() => onDelivery(line)}>Entregar a técnico</button></td></tr>)}</tbody></table></div>{!invoice.lines.length && <p>Esta factura no tiene materiales registrados.</p>}
    <details><summary>Historial de la factura · últimos 100 eventos</summary><ul className={styles.history}>{invoice.events.map((event) => <li key={event.id}><strong>{eventLabel(event.type)}</strong> · {date(event.createdAt)}<small>Usuario: {event.actorId}</small><small>{JSON.stringify(event.detail)}</small></li>)}</ul></details>
  </>}</>;
}
function Delivery({ line, onSaved }: { line: InvoiceLine; onSaved: () => void }) {
  const key = useRef(crypto.randomUUID()), op = useOperation();
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await op.run(async () => { await call("/api/supplies/handoffs", "POST", { requestKey: key.current, lineId: line.id, version: line.version, technician: f.get("technician"), site: f.get("site"), quantity: f.get("quantity"), assignedDate: f.get("assignedDate"), reminderDays: Number(f.get("reminderDays")) }); onSaved(); }); }
  return <><h2>Entregar a un técnico</h2><p>{line.description} · disponible: {quantity(line.availableQuantity)} {line.unit}</p><form onSubmit={submit} className={styles.form}><div className={styles.fields}><label>Técnico que recibió el material<input name="technician" required minLength={2} maxLength={200} /></label><label>Cantidad entregada ({line.unit})<input name="quantity" required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" /></label><label>Sitio (opcional)<input name="site" maxLength={500} /></label><label>Fecha de entrega<input name="assignedDate" type="date" defaultValue={today()} max={today()} required /></label><label>Avisar después de (días)<input name="reminderDays" type="number" min={1} max={365} defaultValue={14} required /></label></div><Feedback error={op.error} /><button disabled={op.busy} className={styles.primary}>{op.busy ? "Guardando…" : "Registrar entrega"}</button></form></>;
}
function eventLabel(type: string) { return ({ CREATED: "Factura registrada", HANDOFF: "Entrega a técnico", CONSUMPTION: "Consumo", RETURN: "Devolución", REVERSAL: "Corrección", FILE_ADDED: "Archivo adjuntado", FILE_REMOVED: "Archivo retirado", DOWNLOADED: "Descarga confirmada", UPLOAD_CONFIRMED: "Carga en Intra confirmada", RESET_DOWNLOAD: "Descarga reabierta", RESET_UPLOAD: "Carga en Intra reabierta" } as Record<string, string>)[type] ?? type; }
function HandoffDetail({ id, onRefresh }: { id: string; onRefresh: () => void }) {
  const [detail, setDetail] = useState<{ handoff: SupplyHandoff; movements: SupplyMovement[]; count: number; page: number } | null>(null), [page, setPage] = useState(1), [action, setAction] = useState("CONSUMPTION"), [forms, setForms] = useState([{ formCode: "", quantity: "" }]), [exhausted, setExhausted] = useState(false);
  const op = useOperation(), key = useRef(crypto.randomUUID());
  const load = useCallback(async () => { setDetail(await call(`/api/supplies/handoffs/${id}?page=${page}`)); }, [id, page]);
  useEffect(() => { void op.run(load); }, [load]); // eslint-disable-line react-hooks/exhaustive-deps
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await op.run(async () => { if (!detail) return; await call(`/api/supplies/handoffs/${id}/movements`, "POST", { requestKey: key.current, version: detail.handoff.version, action, usedDate: f.get("usedDate"), notes: f.get("notes"), ...(action === "RETURN" ? { quantity: f.get("quantity") } : { forms, exhausted }) }); key.current = crypto.randomUUID(); setForms([{ formCode: "", quantity: "" }]); setExhausted(false); await load(); onRefresh(); }); }
  return <><Feedback error={op.error} />{detail ? <><h2>{detail.handoff.line.description}</h2><p><strong>{detail.handoff.technician}</strong> · {detail.handoff.site ?? "Sin sitio"} · factura {detail.handoff.line.invoice.number}</p><div className={styles.balance}>Saldo del técnico: <strong>{quantity(detail.handoff.remaining)} {detail.handoff.line.unit}</strong><small>Entregado: {quantity(detail.handoff.quantityGiven)} · {date(detail.handoff.assignedAt)}</small></div>
    {detail.handoff.status === "ACTIVE" && <form className={styles.form} onSubmit={submit}><h3>Registrar movimiento</h3><select aria-label="Tipo de movimiento" value={action} onChange={(e) => setAction(e.target.value)}><option value="CONSUMPTION">Uso en formularios</option><option value="RETURN">Devolución de material</option></select><div className={styles.fields}><label>Fecha del movimiento<input name="usedDate" type="date" defaultValue={today()} max={today()} required /></label><label>Observaciones {action === "RETURN" ? "(obligatorias)" : "(opcional)"}<input name="notes" required={action === "RETURN"} minLength={action === "RETURN" ? 3 : undefined} maxLength={500} /></label></div>
      {action === "RETURN" ? <label>Cantidad devuelta ({detail.handoff.line.unit})<input name="quantity" inputMode="decimal" required pattern="[0-9]+([.][0-9]{1,3})?" /></label> : <><p>Distribuí la cantidad usada entre uno o varios formularios FO. Si un código no está en el export, quedará pendiente de verificación.</p>{forms.map((form, i) => <div className={styles.line} key={i}><input required aria-label={`Formulario ${i + 1}`} placeholder="FO-26-000000" value={form.formCode} onChange={(e) => setForms((rows) => rows.map((row, j) => j === i ? { ...row, formCode: e.target.value } : row))} /><input required aria-label={`Consumo ${i + 1}`} placeholder={`Cantidad (${detail.handoff.line.unit})`} inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" value={form.quantity} onChange={(e) => setForms((rows) => rows.map((row, j) => j === i ? { ...row, quantity: e.target.value } : row))} /><button type="button" disabled={forms.length <= 1} onClick={() => setForms((rows) => rows.filter((_, j) => j !== i))}>Quitar</button></div>)}<button type="button" disabled={forms.length >= 50} onClick={() => setForms((rows) => [...rows, { formCode: "", quantity: "" }])}>+ Otro formulario</button><label className={styles.check}><input type="checkbox" checked={exhausted} onChange={(e) => { setExhausted(e.target.checked); if (e.target.checked && forms.length === 1) setForms([{ ...forms[0], quantity: detail.handoff.remaining }]); }} /> Se acabó: registrar todo el saldo restante</label></>}
      <button className={styles.primary} disabled={op.busy}>{op.busy ? "Guardando…" : "Guardar movimiento"}</button></form>}
    <h3>Historial de uso y devoluciones</h3>{!detail.count && <p>Todavía no se registraron movimientos de esta entrega.</p>}<ul className={styles.history}>{detail.movements.map((movement) => <li key={movement.id}><strong>{eventLabel(movement.type)} · {quantity(movement.quantity)} {detail.handoff.line.unit}</strong> · {date(movement.usedAt)}{movement.notes && <p>{movement.notes}</p>}{movement.allocations.map((form) => <small key={form.formCode}>{form.formCode} · {quantity(form.quantity)} · {form.verification === "KNOWN_SYTEX" ? "Código presente en export Sytex" : "Verificación pendiente"}</small>)}{movement.reversedBy ? <small className={styles.warning}>Revertido mediante corrección</small> : movement.type !== "REVERSAL" && <button disabled={op.busy} onClick={() => { const notes = window.prompt("Motivo de la corrección (revierte este movimiento y conserva su historial):"); if (notes) void op.run(async () => { await call(`/api/supplies/handoffs/${id}/movements`, "POST", { action: "REVERSAL", requestKey: crypto.randomUUID(), version: detail.handoff.version, movementId: movement.id, notes }); await load(); onRefresh(); }); }}>Corregir este movimiento</button>}{movement.reversalOf && <small>Revierte movimiento {movement.reversalOf}</small>}</li>)}</ul><Pager page={page} count={detail.count} onPage={setPage} />
  </> : <p>Cargando entrega…</p>}</>;
}
