"use client";
import { useEffect,useState,type FormEvent } from 'react';
import type { Material } from '@/contracts/operations';
import { Feedback,opCall,operationsUrl,useCatalog,useOperation,ZoneFavorites } from './operations-common';
import s from './operations.module.css';
const classifications:Record<string,string>={PENDIENTE:'Por definir',INCLUIDO:'Incluido',NO_INCLUIDO:'No incluido'};
const intra:Record<string,string>={PENDIENTE:'Pendiente de descarga',PARCIAL:'Descarga parcial',DESCARGADO:'Descargado en Intra',NO_CORRESPONDE:'No corresponde'};
export function SytexSupplyControl(){
 const zones=useCatalog(),[items,setItems]=useState<Material[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[pending,setPending]=useState(false),[page,setPage]=useState(1),[selected,setSelected]=useState<Material|null>(null);
 const filter=zones.projects.join('|');
 useEffect(()=>{if(!zones.data)return;let active=true;const timer=setTimeout(()=>{setLoading(true);opCall<{items:Material[]}>(operationsUrl('materials',zones.projects)).then(d=>{if(active){setItems(d.items);setError('');setPage(1);}}).catch(e=>{if(active){setError(e.message);setItems([]);}}).finally(()=>{if(active)setLoading(false);});},0);return()=>{active=false;clearTimeout(timer);};},[filter,revision,zones.data]); // eslint-disable-line react-hooks/exhaustive-deps
 const term=search.toLocaleLowerCase(),filtered=items.filter(r=>(!pending||r.missing)&&[r.formulario,r.description,r.siteCode,r.siteName,r.technician,r.review?.invoiceNumber].join(' ').toLocaleLowerCase().includes(term));
 return <section className={s.app}><header className={s.heading}><div><span className={s.kicker}>SYTEX · CONTROL DE CONTEO Y DESCARGA</span><h1>Insumos de cada zona</h1><p className={s.note}>Un registro por formulario, grupo e índice. El control no suma las sincronizaciones repetidas.</p></div><button onClick={()=>setRevision(v=>v+1)} disabled={loading}>Actualizar datos</button></header>
 <ZoneFavorites state={zones}/><Feedback error={error||zones.error}/>
 <p className={s.note}>Intra todavía no está conectado: indicá manualmente la descarga, el conteo y la factura. La inclusión queda “Por definir” hasta contar con el criterio confirmado. Las fotos aparecen únicamente si la fuente entrega un enlace real.</p>
 <div className={s.stats}><div>Insumos únicos<strong>{items.length}</strong></div><div>Para revisar / descargar<strong>{items.filter(r=>r.missing).length}</strong></div><div>Inclusión por definir<strong>{items.filter(r=>!r.review||r.review.classification==='PENDIENTE').length}</strong></div><div>Cambiaron en Sytex<strong>{items.filter(r=>r.changed).length}</strong></div></div>
 <div className={s.toolbar}><input aria-label="Buscar insumo" placeholder="Formulario, material, sitio, técnico o factura…" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><button aria-pressed={pending} onClick={()=>{setPending(v=>!v);setPage(1);}}>Solo pendientes</button>{zones.data&&<a className={s.button} href={operationsUrl('materials',zones.projects,undefined,true)}>Descargar Excel del filtro</a>}</div>
 {loading?<p role="status">Consultando insumos Sytex…</p>:<><div className={s.tableWrap}><table><thead><tr>{['Formulario / zona','Insumo / grupo','Sitio / técnico','Cantidad Sytex','Control / Intra','Factura / foto','Acción'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.slice((page-1)*50,page*50).map(r=><tr key={r.key}><td><strong>{r.formulario}</strong><small>{r.review?.project??(r.projects.join(' / ')||'Zona sin vincular')}</small><small>{r.source} · {new Date(r.syncedAt).toLocaleDateString('es-AR')}</small></td><td><strong>{r.description||'Sin descripción'}</strong><small>{r.group} · {r.index}</small></td><td>{r.siteCode}<small>{r.siteName}</small><small>{r.technician||'Técnico no informado'}</small></td><td>{r.quantity??'Sin cantidad'}<small>Conteo: {r.review?.countedQuantity??'Sin revisar'}</small><small>Intra: {r.review?.intraQuantity??'Sin informar'}</small></td><td>{classifications[r.review?.classification??'PENDIENTE']}<small>{intra[r.review?.intraStatus??'PENDIENTE']}</small>{r.changed&&<span className={s.warning}>Cambió en Sytex</span>}{r.missing&&<small className={s.warning}>Revisión / descarga pendiente</small>}</td><td>{r.review?.invoiceNumber||'Sin número de factura'}<small>{r.files.length} comprobante(s)</small>{r.image?<a href={r.image} target="_blank" rel="noopener noreferrer">Ver foto Sytex ↗</a>:<small>{r.imageDeclared?'Foto declarada, sin enlace disponible':'Sin foto en la fuente'}</small>}</td><td><button onClick={()=>setSelected(r)}>Revisar / cargar factura</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p>No hay insumos con este filtro. Los registros sin zona vinculada requieren revisión del administrador.</p>}<div className={s.pager}><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>{filtered.length} registros · página {page} de {Math.max(1,Math.ceil(filtered.length/50))}</span><button disabled={page*50>=filtered.length} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></>}
 {selected&&zones.data&&<div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-label="Control de insumo"><div className={s.heading}><h2>Revisar insumo</h2><button onClick={()=>setSelected(null)}>Cerrar ✕</button></div><ReviewForm key={selected.key} item={selected} projects={zones.data.projects} onSaved={()=>{setRevision(v=>v+1);setSelected(null);}}/></section></div>}</section>;
}
function ReviewForm({item,projects,onSaved}:{item:Material;projects:string[];onSaved:()=>void}){
 const op=useOperation(),[files,setFiles]=useState<File[]>([]),r=item.review;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await op.run(async()=>{await opCall('/api/operations',{action:'review',key:item.key,project:f.get('project'),classification:f.get('classification'),intraStatus:f.get('intraStatus'),invoiceNumber:f.get('invoiceNumber'),countedQuantity:f.get('countedQuantity')||null,intraQuantity:f.get('intraQuantity')||null,notes:f.get('notes'),version:r?.version??0,sourceHash:item.hash});let saved=0;try{for(const file of files){const form=new FormData();form.set('key',item.key);form.set('file',file);const result=await fetch('/api/operations/files',{method:'POST',body:form});if(!result.ok)throw new Error('No se pudo adjuntar '+file.name+'. El control sí quedó guardado: actualizá y adjuntá los archivos restantes.');saved++;}}catch(e){throw new Error((e instanceof Error?e.message:'No se adjuntó el comprobante.')+' '+saved+' archivo(s) guardados.');}onSaved();});}
 return <form onSubmit={submit}><p><strong>{item.formulario} · {item.description}</strong><br/>{item.siteCode} · {item.siteName}<br/>Cantidad en Sytex: <strong>{item.quantity??'No informada'}</strong></p>{item.changed&&<p className={s.warning}>Cambió el material o la cantidad desde el último control. Volvé a verificar la descarga.</p>}
 <div className={s.fields}><label>Proyecto / zona<select name="project" required defaultValue={r?.project??(item.projects.length===1?item.projects[0]:'')}><option value="">Seleccionar zona</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label>¿Insumo incluido?<select name="classification" defaultValue={r?.classification??'PENDIENTE'}>{Object.entries(classifications).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Estado en Intra<select name="intraStatus" defaultValue={item.changed?'PENDIENTE':r?.intraStatus??'PENDIENTE'}>{Object.entries(intra).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Número de factura<input name="invoiceNumber" maxLength={200} defaultValue={r?.invoiceNumber??''}/></label><label>Cantidad contada<input name="countedQuantity" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" defaultValue={r?.countedQuantity??item.quantity??''}/></label><label>Cantidad descargada en Intra<input name="intraQuantity" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" defaultValue={r?.intraQuantity??''}/></label><label className={s.wide}>Observaciones<textarea name="notes" maxLength={4000} defaultValue={r?.notes??''}/></label><label className={s.wide}>Factura / comprobante (PDF o imagen, hasta 8 MB por archivo)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label></div>
 {!!item.files.length&&<p>Comprobantes guardados: {item.files.map(f=><a key={f.id} href={'/api/operations/files/'+f.id} target="_blank" rel="noopener noreferrer">{f.fileName} · </a>)}</p>}{item.image&&<p><a href={item.image} target="_blank" rel="noopener noreferrer">Abrir foto del técnico en Sytex ↗</a></p>}<p className={s.note}>“Descargado” requiere que coincidan Sytex, conteo e Intra. Si no está incluido, también requiere número de factura. Para “No corresponde”, explicá el motivo.</p><Feedback {...op}/><button className={s.primary} disabled={op.busy}>{op.busy?'Guardando…':'Guardar control y comprobantes'}</button></form>;
}
