"use client";
import { useEffect,useRef,useState,type FormEvent } from 'react';
import type { Material,OperationsCatalog } from '@/contracts/operations';
import { Feedback,opCall,operationsUrl,projectLabel,useCatalog,useOperation,ZoneFilter } from './operations-common';
import { SytexSupplyImport } from './sytex-supply-import';
import { formStatusLabel } from '@/lib/form-status';
import s from './operations.module.css';
const classifications:Record<string,string>={PENDIENTE:'Por definir',INCLUIDO:'Incluido',NO_INCLUIDO:'No incluido'};
const intra:Record<string,string>={PENDIENTE:'Pendiente de descarga',PARCIAL:'Descarga parcial',DESCARGADO:'Descargado en Intra',NO_CORRESPONDE:'No corresponde'};
type SyncStatus={progress?:{done:number;total:number}|null;errorDetail?:string|null;configured:boolean;running:boolean;finishedAt:string|null;result:{projects:number;forms:number;items:number;changed:boolean;since:string}|null;error:string|null};
const SYNC_EVERY_MS=5*60*1000;
const syncErrors:Record<string,string>={SYTEX_CREDENTIAL_REJECTED:'Sytex rechazó el usuario o la clave configurados. Revisá las variables SYTEX_USER y SYTEX_API_KEY.',SYTEX_UNREACHABLE:'No se pudo conectar con Sytex. Se reintenta en unos minutos.',SYTEX_EXPORT_HAS_CONFLICTS:'Sytex devolvió respuestas contradictorias para un mismo insumo; no se guardó esa consulta.'};
function syncText(sync:SyncStatus){
 if(!sync.configured)return 'Sytex en directo sin configurar: se muestran los datos de la última carga manual.';
 if(sync.running)return sync.progress?'Consultando Sytex… descarga '+sync.progress.done+' de '+sync.progress.total+'. Mientras tanto se muestran los datos de la última consulta.':'Consultando Sytex… revisando qué proyectos tienen formularios.';
 if(sync.error)return (syncErrors[sync.error]??(sync.error.startsWith('SYTEX_RESPONSE_')?'Sytex respondió con error '+sync.error.slice(15)+'. Se reintenta en unos minutos.':'La última consulta a Sytex falló. Se reintenta en unos minutos.'))+(sync.errorDetail?' Detalle: '+sync.errorDetail:'');
 if(!sync.finishedAt||!sync.result)return 'Sytex en directo configurado: primera consulta en curso.';
 return 'Sytex en directo · última consulta '+new Date(sync.finishedAt).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})+' · '+sync.result.items+' insumos en '+sync.result.projects+' proyectos desde el '+sync.result.since.split('-').reverse().join('/')+'.';
}
export function SytexSupplyControl(){
 const zones=useCatalog(),[items,setItems]=useState<Material[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[pending,setPending]=useState(false),[page,setPage]=useState(1),[selected,setSelected]=useState<Material|null>(null),[syncRequest,setSyncRequest]=useState(0);
 const filter=zones.projects.join('|');
 const [sync,setSync]=useState<SyncStatus|null>(null),wasRunning=useRef(false);
 // Live data: ask Sytex again when the screen opens and every five minutes while it stays open.
 useEffect(()=>{let active=true,timer:ReturnType<typeof setTimeout>;
  const call=(start:boolean)=>fetch('/api/sytex/sync',{method:start?'POST':'GET',cache:'no-store'}).then(r=>r.ok?r.json() as Promise<SyncStatus>:null).catch(()=>null);
  const tick=async(start:boolean)=>{const before=await call(false);if(!active||!before)return;
   const due=before.configured&&!before.running&&(start||!before.finishedAt||Date.now()-Date.parse(before.finishedAt)>SYNC_EVERY_MS);
   const current=due?await call(true)??before:before;if(!active)return;
   if(wasRunning.current&&!current.running&&current.result?.changed)setRevision(v=>v+1);wasRunning.current=current.running;setSync(current);
   timer=setTimeout(()=>void tick(false),current.running?5000:60000);};
  void tick(syncRequest>0);return()=>{active=false;clearTimeout(timer);};},[syncRequest]);
 useEffect(()=>{if(!zones.data)return;let active=true;const timer=setTimeout(()=>{setLoading(true);opCall<{items:Material[]}>(operationsUrl('materials',zones.projects)).then(d=>{if(active){setItems(d.items);setError('');setPage(1);}}).catch(e=>{if(active){setError(e.message);setItems([]);}}).finally(()=>{if(active)setLoading(false);});},0);return()=>{active=false;clearTimeout(timer);};},[filter,revision,zones.data]); // eslint-disable-line react-hooks/exhaustive-deps
 const term=search.toLocaleLowerCase(),filtered=items.filter(r=>(!pending||r.missing)&&[r.formulario,r.description,r.siteCode,r.siteName,r.technician,r.formStatus,r.review?.invoiceNumber].join(' ').toLocaleLowerCase().includes(term));
 const status=(r:Material)=>r.changed?{text:'Cambió en Sytex',tone:s.badgeWait}:!r.missing?{text:r.review?.intraStatus==='NO_CORRESPONDE'?'No corresponde':'Descargado',tone:r.review?.intraStatus==='NO_CORRESPONDE'?s.badgeOff:s.badgeOk}:r.review?.intraStatus==='PARCIAL'?{text:'Descarga parcial',tone:s.badgeWait}:{text:'Pendiente',tone:s.badgeWait};
 return <section className={s.app}><header className={s.heading}><div><span className={s.kicker}>SYTEX · CONTEO Y DESCARGA EN INTRA</span><h1>Insumos por zona</h1></div><button onClick={()=>{setSyncRequest(v=>v+1);setRevision(v=>v+1);}} disabled={loading||sync?.running}>{sync?.running?'Consultando Sytex…':'Actualizar datos'}</button></header>
 <ZoneFilter state={zones}/><Feedback error={error||zones.error}/>
 {sync&&<p className={s.note} role="status">{syncText(sync)}</p>}
 {zones.data?.admin&&<details className={s.zones}><summary>Cargar Excel de Sytex (carga manual)</summary><SytexSupplyImport onImported={()=>{setRevision(v=>v+1);void opCall<OperationsCatalog>('/api/operations').then(zones.setData).catch(()=>undefined);}}/></details>}
 <div className={s.stats}><div>Insumos<strong>{items.length}</strong></div><div>Pendientes de descarga<strong>{items.filter(r=>r.missing).length}</strong></div><div>Sin definir si es incluido<strong>{items.filter(r=>!r.review||r.review.classification==='PENDIENTE').length}</strong></div><div>Cambiaron en Sytex<strong>{items.filter(r=>r.changed).length}</strong></div></div>
 <div className={s.toolbar}><input aria-label="Buscar insumo" placeholder="Buscar formulario, material, sitio, técnico o factura…" size={44} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><button aria-pressed={pending} onClick={()=>{setPending(v=>!v);setPage(1);}}>Solo pendientes</button>{zones.data&&<a className={s.button} href={operationsUrl('materials',zones.projects,undefined,true)}>Descargar Excel</a>}</div>
 {loading?<p role="status">Consultando insumos…</p>:<><div className={s.tableWrap}><table className={s.compact}><thead><tr>{['Formulario','Cell ID','Estado','Tipo','Respuesta','Fecha','Factura','Intra',''].map((t,i)=><th key={i}>{t}</th>)}</tr></thead><tbody>{filtered.slice((page-1)*50,page*50).map(r=>{const st=status(r),zone=r.review?.project??(r.projects.length===1?r.projects[0]:'');return <tr key={r.key}><td className={s.nowrap}><strong>{r.link?<a href={r.link} target="_blank" rel="noopener noreferrer" title="Abrir en Sytex">{r.formulario} ↗</a>:r.formulario}</strong></td><td>{r.siteCode}<small>{r.siteName}</small></td><td>{formStatusLabel(r.formStatus)||'—'}</td><td className={s.nowrap}>{zone?projectLabel(zone):'Sin zona'}</td><td><strong>{r.description||'Sin descripción'}</strong><small>Cantidad: {r.quantity??'—'}{r.provider&&' · '+r.provider}</small></td><td className={s.nowrap}>{r.editedAt?r.editedAt.slice(0,10).split('-').reverse().join('/'):'—'}</td><td>{r.review?.invoiceNumber||'Sin factura'}{r.files.length>0&&<small>{r.files.length} comprobante(s)</small>}</td><td><span className={s.badge+' '+st.tone}>{st.text}</span></td><td><button onClick={()=>setSelected(r)}>Revisar</button></td></tr>;})}</tbody></table></div>{!filtered.length&&<p>No hay insumos con este filtro.</p>}<div className={s.pager}><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>{filtered.length} registros · página {page} de {Math.max(1,Math.ceil(filtered.length/50))}</span><button disabled={page*50>=filtered.length} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></>}
 {selected&&zones.data&&<div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-label="Control de insumo"><div className={s.heading}><h2>Revisar insumo</h2><button onClick={()=>setSelected(null)}>Cerrar ✕</button></div><ReviewForm key={selected.key} item={selected} projects={zones.data.projects} onSaved={()=>{setRevision(v=>v+1);setSelected(null);}}/></section></div>}</section>;
}
function ReviewForm({item,projects,onSaved}:{item:Material;projects:string[];onSaved:()=>void}){
 const op=useOperation(),[files,setFiles]=useState<File[]>([]),r=item.review,[status,setStatus]=useState(item.changed?'PENDIENTE':r?.intraStatus==='PARCIAL'?'PENDIENTE':r?.intraStatus??'PENDIENTE');
 const knownProject=r?.project??(item.projects.length===1?item.projects[0]:'');
 // The coordinator only states the invoice and whether it was downloaded; the rest follows from that.
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),invoice=String(f.get('invoiceNumber')??'').trim(),counted=item.quantity??'0';
  const classification=invoice?'NO_INCLUIDO':status==='PENDIENTE'?r?.classification??'PENDIENTE':'INCLUIDO';
  await op.run(async()=>{await opCall('/api/operations',{action:'review',key:item.key,project:knownProject||f.get('project'),classification,intraStatus:status,invoiceNumber:invoice,countedQuantity:status==='DESCARGADO'?counted:r?.countedQuantity??null,intraQuantity:status==='DESCARGADO'?counted:null,notes:f.get('notes')??'',version:r?.version??0,sourceHash:item.hash});let saved=0;try{for(const file of files){const form=new FormData();form.set('key',item.key);form.set('file',file);const result=await fetch('/api/operations/files',{method:'POST',body:form});if(!result.ok)throw new Error('No se pudo adjuntar '+file.name+'. El control sí quedó guardado: actualizá y adjuntá los archivos restantes.');saved++;}}catch(e){throw new Error((e instanceof Error?e.message:'No se adjuntó el comprobante.')+' '+saved+' archivo(s) guardados.');}onSaved();});}
 return <form onSubmit={submit}><p><strong>{item.formulario} · {item.description}</strong><br/>{item.siteCode} · {item.siteName}{knownProject&&' · '+projectLabel(knownProject)}<br/>Cantidad en Sytex: <strong>{item.quantity??'No informada'}</strong>{item.technician&&' · '+item.technician}</p>{item.changed&&<p className={s.warning}>Cambió el material o la cantidad en Sytex desde el último control.</p>}
 <div className={s.fields}>{!knownProject&&<label className={s.wide}>Proyecto<select name="project" required defaultValue=""><option value="">Seleccionar proyecto</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label>}
 <label>Número de factura<input name="invoiceNumber" maxLength={200} defaultValue={r?.invoiceNumber??''} placeholder="Solo si el insumo no está incluido"/></label>
 <label>¿Descargado en Intra?<select aria-label="¿Descargado en Intra?" value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDIENTE">No, pendiente</option><option value="DESCARGADO">Sí, descargado</option><option value="NO_CORRESPONDE">No corresponde descargar</option></select></label>
 {status==='NO_CORRESPONDE'&&<label className={s.wide}>Motivo<textarea name="notes" required maxLength={4000} defaultValue={r?.notes??''}/></label>}</div>
 <details className={s.more}><summary>Adjuntar comprobante{status!=='NO_CORRESPONDE'&&' u observaciones'}</summary><div className={s.fields}>{status!=='NO_CORRESPONDE'&&<label className={s.wide}>Observaciones<textarea name="notes" maxLength={4000} defaultValue={r?.notes??''}/></label>}<label className={s.wide}>Factura o comprobante (PDF o imagen, hasta 8 MB)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label></div></details>
 {!!item.files.length&&<p>Comprobantes guardados: {item.files.map(f=><a key={f.id} href={'/api/operations/files/'+f.id} target="_blank" rel="noopener noreferrer">{f.fileName} · </a>)}</p>}{item.image&&<p><a href={item.image} target="_blank" rel="noopener noreferrer">Abrir foto del técnico en Sytex ↗</a></p>}<Feedback {...op}/><button className={s.primary} disabled={op.busy}>{op.busy?'Guardando…':'Guardar'}</button></form>;
}
