"use client";
import { useEffect,useRef,useState,type FormEvent } from 'react';
import type { Material } from '@/contracts/operations';
import { Feedback,opCall,operationsUrl,projectLabel,useCatalog,useOperation,ZoneFilter } from './operations-common';
import s from './operations.module.css';
const classifications:Record<string,string>={PENDIENTE:'Por definir',INCLUIDO:'Incluido',NO_INCLUIDO:'No incluido'};
const intra:Record<string,string>={PENDIENTE:'Pendiente de descarga',PARCIAL:'Descarga parcial',DESCARGADO:'Descargado en Intra',NO_CORRESPONDE:'No corresponde'};
type SyncStatus={configured:boolean;running:boolean;finishedAt:string|null;result:{projects:number;forms:number;items:number;changed:boolean;since:string}|null;error:string|null};
const SYNC_EVERY_MS=5*60*1000;
const syncErrors:Record<string,string>={SYTEX_CREDENTIAL_REJECTED:'Sytex rechazó la clave configurada. Revisá la variable SYTEX_AUTHORIZATION.',SYTEX_UNREACHABLE:'No se pudo conectar con Sytex. Se reintenta en unos minutos.',SYTEX_EXPORT_HAS_CONFLICTS:'Sytex devolvió respuestas contradictorias para un mismo insumo; no se guardó esa consulta.'};
function syncText(sync:SyncStatus){
 if(!sync.configured)return 'Sytex en directo sin configurar: se muestran los datos de la última carga manual.';
 if(sync.running)return 'Consultando Sytex…';
 if(sync.error)return syncErrors[sync.error]??'La última consulta a Sytex falló. Se reintenta en unos minutos.';
 if(!sync.finishedAt||!sync.result)return 'Sytex en directo configurado: primera consulta en curso.';
 return 'Sytex en directo · última consulta '+new Date(sync.finishedAt).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})+' · '+sync.result.items+' insumos en '+sync.result.projects+' proyectos desde el '+sync.result.since.split('-').reverse().join('/')+'.';
}
export function SytexSupplyControl(){
 const zones=useCatalog(),[items,setItems]=useState<Material[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[pending,setPending]=useState(false),[page,setPage]=useState(1),[selected,setSelected]=useState<Material|null>(null),[syncRequest,setSyncRequest]=useState(0);
 const filter=zones.projects.join('|');
 const [sync,setSync]=useState<SyncStatus|null>(null),wasRunning=useRef(false);
 // Live data: ask Sytex again when the screen opens and every five minutes while it stays open.
 useEffect(()=>{let active=true,timer:ReturnType<typeof setTimeout>;
  const call=(start:boolean)=>fetch('/api/sytex/sync',{method:start?'POST':'GET',cache:'no-store'}).then(r=>r.ok?r.json() as Promise<SyncStatus>:null).catch(()=>null);
  const tick=async(start:boolean)=>{const before=await call(false);if(!active||!before)return;
   const due=before.configured&&!before.running&&(start||!before.finishedAt||Date.now()-Date.parse(before.finishedAt)>SYNC_EVERY_MS);
   const current=due?await call(true)??before:before;if(!active)return;
   if(wasRunning.current&&!current.running&&current.result?.changed)setRevision(v=>v+1);wasRunning.current=current.running;setSync(current);
   timer=setTimeout(()=>void tick(false),current.running?5000:60000);};
  void tick(syncRequest>0);return()=>{active=false;clearTimeout(timer);};},[syncRequest]);
 useEffect(()=>{if(!zones.data)return;let active=true;const timer=setTimeout(()=>{setLoading(true);opCall<{items:Material[]}>(operationsUrl('materials',zones.projects)).then(d=>{if(active){setItems(d.items);setError('');setPage(1);}}).catch(e=>{if(active){setError(e.message);setItems([]);}}).finally(()=>{if(active)setLoading(false);});},0);return()=>{active=false;clearTimeout(timer);};},[filter,revision,zones.data]); // eslint-disable-line react-hooks/exhaustive-deps
 const term=search.toLocaleLowerCase(),filtered=items.filter(r=>(!pending||r.missing)&&[r.formulario,r.description,r.siteCode,r.siteName,r.technician,r.review?.invoiceNumber].join(' ').toLocaleLowerCase().includes(term));
 const status=(r:Material)=>r.changed?{text:'Cambió en Sytex',tone:s.badgeWait}:!r.missing?{text:r.review?.intraStatus==='NO_CORRESPONDE'?'No corresponde':'Descargado',tone:r.review?.intraStatus==='NO_CORRESPONDE'?s.badgeOff:s.badgeOk}:r.review?.intraStatus==='PARCIAL'?{text:'Descarga parcial',tone:s.badgeWait}:{text:'Pendiente',tone:s.badgeWait};
 return <section className={s.app}><header className={s.heading}><div><span className={s.kicker}>SYTEX · CONTEO Y DESCARGA EN INTRA</span><h1>Insumos por zona</h1></div><button onClick={()=>{setSyncRequest(v=>v+1);setRevision(v=>v+1);}} disabled={loading||sync?.running}>{sync?.running?'Consultando Sytex…':'Actualizar datos'}</button></header>
 <ZoneFilter state={zones}/><Feedback error={error||zones.error}/>
 {sync&&<p className={s.note} role="status">{syncText(sync)}</p>}
 <div className={s.stats}><div>Insumos<strong>{items.length}</strong></div><div>Pendientes de descarga<strong>{items.filter(r=>r.missing).length}</strong></div><div>Sin definir si es incluido<strong>{items.filter(r=>!r.review||r.review.classification==='PENDIENTE').length}</strong></div><div>Cambiaron en Sytex<strong>{items.filter(r=>r.changed).length}</strong></div></div>
 <div className={s.toolbar}><input aria-label="Buscar insumo" placeholder="Buscar formulario, material, sitio, técnico o factura…" size={44} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/><button aria-pressed={pending} onClick={()=>{setPending(v=>!v);setPage(1);}}>Solo pendientes</button>{zones.data&&<a className={s.button} href={operationsUrl('materials',zones.projects,undefined,true)}>Descargar Excel</a>}</div>
 {loading?<p role="status">Consultando insumos…</p>:<><div className={s.tableWrap}><table className={s.compact}><thead><tr>{['Formulario','Zona','Insumo','Sitio','Cantidad','Incluido','Intra','Factura',''].map((t,i)=><th key={i}>{t}</th>)}</tr></thead><tbody>{filtered.slice((page-1)*50,page*50).map(r=>{const st=status(r),zone=r.review?.project??(r.projects.length===1?r.projects[0]:'');return <tr key={r.key}><td className={s.nowrap}><strong>{r.formulario}</strong></td><td className={s.nowrap}>{zone?projectLabel(zone):'Sin zona'}</td><td><strong>{r.description||'Sin descripción'}</strong></td><td>{r.siteCode}<small>{r.siteName}</small></td><td className={s.nowrap}>{r.quantity??'—'}{r.review&&<small>Contado {r.review.countedQuantity??'—'} · Intra {r.review.intraQuantity??'—'}</small>}</td><td className={s.nowrap}>{classifications[r.review?.classification??'PENDIENTE']}</td><td><span className={s.badge+' '+st.tone}>{st.text}</span></td><td>{r.review?.invoiceNumber||'—'}{r.files.length>0&&<small>{r.files.length} comprobante(s)</small>}{r.image&&<small><a href={r.image} target="_blank" rel="noopener noreferrer">Foto ↗</a></small>}</td><td><button onClick={()=>setSelected(r)}>Revisar</button></td></tr>;})}</tbody></table></div>{!filtered.length&&<p>No hay insumos con este filtro.</p>}<div className={s.pager}><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Anterior</button><span>{filtered.length} registros · página {page} de {Math.max(1,Math.ceil(filtered.length/50))}</span><button disabled={page*50>=filtered.length} onClick={()=>setPage(v=>v+1)}>Siguiente</button></div></>}
 {selected&&zones.data&&<div className={s.overlay}><section className={s.dialog} role="dialog" aria-modal="true" aria-label="Control de insumo"><div className={s.heading}><h2>Revisar insumo</h2><button onClick={()=>setSelected(null)}>Cerrar ✕</button></div><ReviewForm key={selected.key} item={selected} projects={zones.data.projects} onSaved={()=>{setRevision(v=>v+1);setSelected(null);}}/></section></div>}</section>;
}
function ReviewForm({item,projects,onSaved}:{item:Material;projects:string[];onSaved:()=>void}){
 const op=useOperation(),[files,setFiles]=useState<File[]>([]),r=item.review;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await op.run(async()=>{await opCall('/api/operations',{action:'review',key:item.key,project:f.get('project'),classification:f.get('classification'),intraStatus:f.get('intraStatus'),invoiceNumber:f.get('invoiceNumber'),countedQuantity:f.get('countedQuantity')||null,intraQuantity:f.get('intraQuantity')||null,notes:f.get('notes'),version:r?.version??0,sourceHash:item.hash});let saved=0;try{for(const file of files){const form=new FormData();form.set('key',item.key);form.set('file',file);const result=await fetch('/api/operations/files',{method:'POST',body:form});if(!result.ok)throw new Error('No se pudo adjuntar '+file.name+'. El control sí quedó guardado: actualizá y adjuntá los archivos restantes.');saved++;}}catch(e){throw new Error((e instanceof Error?e.message:'No se adjuntó el comprobante.')+' '+saved+' archivo(s) guardados.');}onSaved();});}
 return <form onSubmit={submit}><p><strong>{item.formulario} · {item.description}</strong><br/>{item.siteCode} · {item.siteName}<br/>Técnico: {item.technician||'no informado'} · {item.group}<br/>Cantidad en Sytex: <strong>{item.quantity??'No informada'}</strong></p>{item.changed&&<p className={s.warning}>Cambió el material o la cantidad desde el último control. Volvé a verificar la descarga.</p>}
 <div className={s.fields}><label>Proyecto / zona<select name="project" required defaultValue={r?.project??(item.projects.length===1?item.projects[0]:'')}><option value="">Seleccionar zona</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label><label>¿Insumo incluido?<select name="classification" defaultValue={r?.classification??'PENDIENTE'}>{Object.entries(classifications).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Estado en Intra<select name="intraStatus" defaultValue={item.changed?'PENDIENTE':r?.intraStatus??'PENDIENTE'}>{Object.entries(intra).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Número de factura<input name="invoiceNumber" maxLength={200} defaultValue={r?.invoiceNumber??''}/></label><label>Cantidad contada<input name="countedQuantity" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" defaultValue={r?.countedQuantity??item.quantity??''}/></label><label>Cantidad descargada en Intra<input name="intraQuantity" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,3})?" defaultValue={r?.intraQuantity??''}/></label><label className={s.wide}>Observaciones<textarea name="notes" maxLength={4000} defaultValue={r?.notes??''}/></label><label className={s.wide}>Factura / comprobante (PDF o imagen, hasta 8 MB por archivo)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label></div>
 {!!item.files.length&&<p>Comprobantes guardados: {item.files.map(f=><a key={f.id} href={'/api/operations/files/'+f.id} target="_blank" rel="noopener noreferrer">{f.fileName} · </a>)}</p>}{item.image&&<p><a href={item.image} target="_blank" rel="noopener noreferrer">Abrir foto del técnico en Sytex ↗</a></p>}<p className={s.note}>“Descargado” requiere que coincidan Sytex, conteo e Intra. Si no está incluido, también requiere número de factura. Para “No corresponde”, explicá el motivo.</p><Feedback {...op}/><button className={s.primary} disabled={op.busy}>{op.busy?'Guardando…':'Guardar control y comprobantes'}</button></form>;
}
